---
- hosts: all
  become: true

  vars:
    user_name: myuser

  tasks:
    - name: Install packages on Ubuntu
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - python3
        - python3-pip
        - openjdk-11-jdk
      when: ansible_distribution == "Ubuntu"

    - name: Install packages on CentOS
      dnf:
        name: "{{ item }}"
        state: latest
      loop:
        - python3
        - python3-pip
        - java-11-openjdk-devel
      when: ansible_distribution == "CentOS"

    - name: Set default MOTD
      copy:
        content: "ANsible Managed node by Adano"
        dest: /etc/motd

    - name: Create a new user
      user:
         name: "{{ user_name }}"
         comment: "New User"
         state: present
         createhome: yes
         shell: /bin/bash
